services:
  - type: web
    name: askvirabot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.9
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENWEATHERMAP_API_KEY
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: TIMEZONE
        value: Europe/Istanbul
