# utils/callbacks.py

# --- MAIN MENU ---
MENU_TOOLS = "MENU:TOOLS"
MENU_GAMES = "MENU:GAMES"
MENU_LANGUAGE = "MENU:LANG"
MENU_DEVELOPER = "MENU:DEV"
MENU_AI = "MENU:AI"
MENU_HELP = "MENU:HELP"
MENU_NOTES = "MENU:NOTES"
MENU_MAIN = "MENU:MAIN"  # Back to Main Menu

# --- TOOLS ---
TOOL_NOTES = "TOOL:NOTES"
TOOL_REMINDER = "TOOL:REMINDER"
TOOL_QR = "TOOL:QR"
TOOL_PDF = "TOOL:PDF"
TOOL_WEATHER = "TOOL:WEATHER"
TOOL_METRO = "TOOL:METRO"
TOOL_VIDEO = "TOOL:VIDEO"
TOOL_SHAZAM = "TOOL:SHAZAM"
TOOL_BACK = "TOOL:BACK"  # Back to Tools Menu

# --- GAMES ---
GAME_XOX = "GAME:XOX"
GAME_DICE = "GAME:DICE"
GAME_COINFLIP = "GAME:COIN"
GAME_TKM = "GAME:TKM"
GAME_SUDOKU = "GAME:SUDOKU"
GAME_SNAKE = "GAME:SNAKE"
GAME_2048 = "GAME:2048"
GAME_FLAPPY = "GAME:FLAPPY"
GAME_RUNNER = "GAME:RUNNER"
GAME_STATS = "GAME:STATS"
GAME_BACK = "GAME:BACK"  # Back to Games Menu

# --- NOTES ---
NOTE_ADD = "NOTE:ADD"
NOTE_EDIT = "NOTE:EDIT"
NOTE_EDIT_MENU = "NOTE:EDIT_MENU"
NOTE_LIST = "NOTE:LIST"
NOTE_DELETE_MENU = "NOTE:DELETE_MENU"
NOTE_DELETE = "NOTE:DELETE"
NOTE_BACK = "NOTE:BACK"  # Back to Notes Menu

# --- SETTINGS / LANGUAGE ---
LANG_TR = "LANG:TR"
LANG_EN = "LANG:EN"
LANG_RU = "LANG:RU"
LANG_PREFIX = "LANG:"

# --- PDF ---
PDF_TEXT = "PDF:TEXT"
PDF_IMAGE = "PDF:IMAGE"
PDF_DOC = "PDF:DOC"
PDF_BACK = "PDF:BACK"  # Back to PDF Menu

# --- REMINDER ---
REMINDER_ADD = "REM:ADD"
REMINDER_LIST = "REM:LIST"
REMINDER_DELETE_MENU = "REM:DEL_MENU"  # Menu to select which to delete
REMINDER_DELETE_EXEC = "REM:DEL_EXEC"  # Execute delete
REMINDER_BACK = "REM:BACK"

# --- METRO ---
METRO_MENU = "METRO:MENU"
METRO_LINES = "METRO:LINES"
METRO_FAV_ADD = "METRO:FAV:ADD"
METRO_FAV_LIST = "METRO:FAV:LIST"
METRO_FAV_EDIT = "METRO:FAV:EDIT"  # Menu to delete favorites
METRO_FAV_DEL = "METRO:FAV:DEL"  # Execute delete favorite
METRO_FAV_USE = "METRO:FAV:USE"  # Quick access

# Dynamic prefixes (usage: PREFIX:ID)
METRO_LINE_PREFIX = "METRO:LINE:"
METRO_STATION_PREFIX = "METRO:STAT:"
METRO_DIR_PREFIX = "METRO:DIR:"

# --- VIDEO DOWNLOADER ---
VIDEO_TIKTOK = "VID:TIKTOK"
VIDEO_TWITTER = "VID:TWITTER"
VIDEO_INSTAGRAM = "VID:INSTA"
VIDEO_BACK = "VID:BACK"

# --- AI ---
AI_START = "AI:START"
AI_END = "AI:END"
AI_BACK = "AI:BACK"
